extends:
  - "${BASH_DEV_ENV_ROOT_DIR}/src/_commandDefinitions/installScript.yaml"

vars:
  SRC_FILE_PATH: src/_installScripts/Git/GitDefaultConfig-binary.yaml

compilerConfig:
  targetFile: "${BASH_DEV_ENV_ROOT_DIR}/installScripts/GitDefaultConfig"
  relativeRootDirBasedOnTargetDir: ..
binData:
  commands:
    default:
      functionName: GitDefaultConfigCommand
      version: "3.0"
      copyrightBeginYear: 2024
      beforeParseCallbacks:
        - gitDefaultConfigBeforeParseCallback
      definitionFiles:
        11: ${BASH_DEV_ENV_ROOT_DIR}/src/_installScripts/Git/GitDefaultConfig.sh
      commandName: GitDefaultConfig
