extends:
  - "${BASH_DEV_ENV_ROOT_DIR}/src/_commandDefinitions/installScript.yaml"

vars:
  SRC_FILE_PATH: src/_installScripts/AwsDefaultConfig/AwsDefaultConfig-binary.yaml

compilerConfig:
  targetFile: "${BASH_DEV_ENV_ROOT_DIR}/installScripts/AwsDefaultConfig"
  relativeRootDirBasedOnTargetDir: ..
binData:
  commands:
    default:
      functionName: AwsDefaultConfigCommand
      version: "3.0"
      copyrightBeginYear: 2024
      definitionFiles:
        11: ${BASH_DEV_ENV_ROOT_DIR}/src/_installScripts/AwsDefaultConfig/AwsDefaultConfig.sh
      commandName: AwsDefaultConfig
