extends:
  - "${BASH_DEV_ENV_ROOT_DIR}/src/_commandDefinitions/upgradeGithubRelease.yaml"

vars:
  SRC_FILE_PATH: src/_installScripts/Docker/DockerCompose-binary.yaml

compilerConfig:
  targetFile: "${BASH_DEV_ENV_ROOT_DIR}/installScripts/DockerCompose"
  relativeRootDirBasedOnTargetDir: ..
binData:
  commands:
    default:
      functionName: DockerComposeCommand
      version: "3.0"
      copyrightBeginYear: 2024
      definitionFiles:
        11: ${BASH_DEV_ENV_ROOT_DIR}/src/_installScripts/Docker/DockerCompose.sh
      commandName: DockerCompose
