---
repos:
  - repo: local
    hooks:
      - id: remove-megalinter-containers
        name: remove-megalinter-containers
        entry:
          bash -c 'set -x && docker ps -a -q --filter="name=megalinter" | xargs
          -r docker rm || true'
        language: system
        always_run: true
        require_serial: true
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: |
          (?x)^(
            conf\/localAppData\/Packages\/Microsoft.WindowsTerminal_8wekyb3d8bbwe\/LocalState\/originalSettings.json |
            conf\/.vscode\/settings.json
          )$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        # shellcheck does not validate correctly zsh files
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: (?x)^( vendor/.*| \.tpl| ^bin/.*| .\.zsh| \.zshrc| install )$

      - id: shfmt
        args: [-i, '2', -ci]
        exclude: (.\.zsh$|/\.zshrc$)

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: build-sh-files
        name: build-sh-files
        entry: bash -c './.github/workflows/buildBinFiles.sh'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: install-requirements
        name: install-requirements
        entry: bash -c './bin/installRequirements'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  - repo: local
    hooks:
      - id: build-doc-files
        name: build-doc-files
        entry: bash -c './bin/doc'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        verbose: true

  ## Python, Polyglot, Git, pre-commit
  - repo: https://github.com/ScribeMD/pre-commit-hooks
    rev: 0.16.3
    hooks:
      - id: megalinter-incremental
        args: [--flavor, terraform, --release, v6.16.0]
        stages:
          - commit
      - id: megalinter-full
        args: [--flavor, terraform, --release, v6.16.0]
        stages:
          - push

  - repo: local
    hooks:
      - id: remove-megalinter-containers-after-run
        name: remove-megalinter-containers
        entry:
          bash -c 'set -x && docker ps -a -q --filter="name=megalinter" | xargs
          -r docker rm || true'
        language: system
        always_run: true
        require_serial: true
        verbose: true
