---
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, manual]
minimum_pre_commit_version: 3.5.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: |
          (?x)^(
            conf\/localAppData\/Packages\/Microsoft.WindowsTerminal_8wekyb3d8bbwe\/LocalState\/originalSettings.json |
            conf\/.vscode\/settings.json
          )$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [-i, '2', -ci]
        # x modifier: extended. Spaces and text after a # in the pattern are ignored
        exclude: |
          (?x)(
            ^vendor/|
            ^bin/|
            ^distro$|
            ^install$|
            ^installScripts/|
            \.tpl$ |
            /testsData/
          )
        stages: [pre-commit]

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        exclude: /testsData/

  - repo: https://github.com/fchastanet/bash-tools-framework
    rev: 2.3.2
    hooks:
      - id: fixShebangExecutionBit
      - id: fixShebangExecutionBitGithubActions
      - id: awkLint
      - id: buildShFiles
      - id: buildShFilesGithubAction
      - id: shellcheckLint
      - id: shellcheckLintGithubAction
      - id: frameworkLinter
        args:
          [
            --expected-warnings-count,
            '3',
            --format,
            plain,
            --theme,
            default-force,
            --display-level,
            WARNING,
          ]
      - id: frameworkLinterGithubAction
        args:
          [
            --expected-warnings-count,
            '3',
            --format,
            checkstyle,
            --theme,
            default-force,
            --display-level,
            WARNING,
          ]
      - id: plantuml
      - id: megalinterCheckVersion
      - id: megalinterGithubAction
