[[IgnoredVulns]]
id = "GHSA-3jxr-9vmj-r5cp"
ignoreUntil = 2027-01-01
reason = "ignore brace-expansion vulnerability in bash-dev-env"

[[IgnoredVulns]]
id = "GHSA-mh99-v99m-4gvg"
ignoreUntil = 2027-01-01
reason = "ignore brace-expansion vulnerability in bash-dev-env"

[[IgnoredVulns]]
id = "GHSA-rgw5-rvv9-x895"
ignoreUntil = 2027-01-01
reason = "ignore brace-expansion vulnerability in bash-dev-env"
