extends:
  - "${BASH_DEV_ENV_ROOT_DIR}/src/_commandDefinitions/installScript.yaml"

vars:
  SRC_FILE_PATH: src/_installScripts/_Configs/KubeDefaultConfig-binary.yaml

compilerConfig:
  targetFile: "${BASH_DEV_ENV_ROOT_DIR}/installScripts/KubeDefaultConfig"
  relativeRootDirBasedOnTargetDir: ..
binData:
  commands:
    default:
      functionName: KubeDefaultConfigCommand
      version: "3.0"
      copyrightBeginYear: 2024
      beforeParseCallbacks:
        - kubeBeforeParseCallback
      definitionFiles:
        11: ${BASH_DEV_ENV_ROOT_DIR}/src/_installScripts/_Configs/KubeDefaultConfig.sh
      commandName: KubeDefaultConfig
