extends:
  - "${BASH_DEV_ENV_ROOT_DIR}/src/_commandDefinitions/installScript.yaml"

vars:
  SRC_FILE_PATH: src/_installScripts/_Configs/MotdDefaultConfig-binary.yaml

compilerConfig:
  targetFile: "${BASH_DEV_ENV_ROOT_DIR}/installScripts/MotdDefaultConfig"
  relativeRootDirBasedOnTargetDir: ..
binData:
  commands:
    default:
      functionName: MotdDefaultConfigCommand
      version: "3.0"
      copyrightBeginYear: 2024
      definitionFiles:
        11: ${BASH_DEV_ENV_ROOT_DIR}/src/_installScripts/_Configs/MotdDefaultConfig.sh
      commandName: MotdDefaultConfig
