---
name: Build and Deploy Documentation

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    uses: fchastanet/my-documents/.github/workflows/build-site-action.yml@master
    with:
      site-name: "bash-dev-env"
      checkout-repo: "fchastanet/bash-dev-env"
      site-dir: "_site-content"
    permissions:
      contents: read
      pages: write
      id-token: write
