---
# Lint the code base and launch unit test at each push or pull request
name: Lint and test
on:
  push:
    # execute when pushing only branches, not tags
    branches:
      - '**'
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-22.04
    permissions:
      # needed by ouzi-dev/commit-status-updater@v2
      statuses: write
      # needed by peter-evans/create-pull-request@v5
      pull-requests: write
      # needed by peter-evans/create-pull-request@v5
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # kics-scan ignore-line
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        # kics-scan ignore-line
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install vendors
        run: |
          set -exo pipefail
          ./bin/installRequirements

      # only if pre-commit
      - name: Set up Python
        if: matrix.runPrecommitTests
        # kics-scan ignore-line
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install pre-commit
        if: matrix.runPrecommitTests
        run: pip install pre-commit

      # kics-scan ignore-line
      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: lint
          status: pending

      - name: Checkstyle aggregation
        # kics-scan ignore-line
        uses: lcollins/checkstyle-github-action@v2.0.0
        with:
          path: 'artifacts/**/*.xml'

      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: linter-reports
          path: |
            logs/*.xml
            logs/*.log

      - name: Create Pull Request
        if: matrix.runPrecommitTests && failure()
        # kics-scan ignore-line
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update/pre-commit-fixes
          title: lint fixes
          commit-message: Auto-update lint fixes
          body: |
            some auto fixes have been generated during pre-commit run
          labels: updates

      - uses: ouzi-dev/commit-status-updater@v2
        if: always()
        with:
          name: lint
          status: ${{ job.status }}
